# ==========================================
# Startup
# ----------
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'tpope/vim-sleuth'

# ==========================================
# Completion
# ----------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_add = 'let g:deoplete#enable_at_startup = 1'
hook_source = 'source $VIMPATH/plugins/deoplete.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"
on_source = 'deoplete.nvim'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"
on_source = 'deoplete.nvim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
lazy = 1

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_add = '''
let g:racer_experimental_completer = 1

au FileType rust nmap gd <Plug>(rust-def)
au FileType rust nmap gs <Plug>(rust-def-split)
au FileType rust nmap gx <Plug>(rust-def-vertical)
au FileType rust nmap <leader>gd <Plug>(rust-doc)
'''


# ==========================================
# Commands
# --------
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = 'nerdtree-git-plugin'
on_map = { n = '<Plug>' }
hook_post_source = 'source $VIMPATH/plugins/nerdtree.vim'
hook_add = '''
    map <F2> :NERDTreeToggle<CR>
    nmap  <leader>t :NERDTreeToggle<CR>
    nmap  <leader>f :NERDTreeFind<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
on_source = 'nerdtree'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
lazy = 1

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = [ 'Files', 'GFiles?', 'Buffers', 'Tags', 'BTags', 'Marks' ]
depends = 'fzf'
hook_post_source = 'source $VIMPATH/plugins/fzf.vim'
hook_add = '''
nnoremap <C-p> :Files<CR>
nnoremap <C-g> :GFiles?<CR>
nnoremap <C-b> :Buffers<CR>
nnoremap <C-x> :Tags<CR>
nnoremap <leader>l :BTags<CR>
nnoremap <C-m> :Marks<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_post_source = 'source $VIMPATH/plugins/tagbar.vim'
on_cmd = 'TagbarOpenAutoClose'
hook_add = '''
let g:tagbar_width = 40
nnoremap <F3> :TagbarOpenAutoClose<CR>
" Also use h/l to open/close folds
let g:tagbar_map_closefold = ['h', '-', 'zc']
let g:tagbar_map_openfold = ['l', '+', 'zo']
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = 'Gstatus'

# ==========================================
# UI
# ----------
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_path = '.*'
hook_source = '''
let g:gitgutter_map_keys = 0
let g:gitgutter_sh = $SHELL
'''

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'
